package javaMyBeloved;
public class javaMyBeloved{
  public static void main(String[] args){
    System.out.println("                     https://www.youtube.com/watch?v=m4-HM_sCvtQ                                     ");
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                 :^~!777!~^.         ");
    System.out.println("                                                                             :!J5555YYY55PP5?!:      ");
    System.out.println("                                                                          ^755Y7~:..   ..:!JPPY7.    ");
    System.out.println("                                                        ..::::::..     .!Y5J~.              :JGPY:   ");
    System.out.println("                                                    .!J5PPP55YYYYYYJ?7?5Y!:                   !GGJ.  ");
    System.out.println("                                                  :?GBPJ!~^:::::::^~!7!^.........              7GG!: ");
    System.out.println("                                  .:^~~~~^:.     :PBP!^:::^^^::::::.....:............          .5GY  ");
    System.out.println("                              .:~7777!!77?JJ!:   YB5~^^^^^^^^^^::::::::::::::.............      7GP! ");
    System.out.println("                            :!??!^:.      .~JY! .GB7^~^^^^^^^^^^^:::::::::::::::..............  !GP! ");
    System.out.println("         ...::::::....   .^7J7^.             ~Y?^GB!^~^^^^^^^^^^^^^::::::::.::.::::............ ?GY  ");
    System.out.println("     :~!?JJJ??7777!!!!!!!??!:                 :PBPB?^~~~~~~^^^^^^^^~!^~~~~~!7?J:::::::.........^PG^  ");
    System.out.println("   ^?Y55J!^:..       ...::. .~                 ^BGGP~~~~~~~^~^^^^^^~J?JJY7J~7!7^:::.:.::7^..:.:5G!   ");
    System.out.println(" .JP55J^                    ^?  ..              ?#5BJ~~~~~~~~~^^^^^!7~~^^^^!^^^~~~!?7??7JJ.:.:5G!    ");
    System.out.println(" JG5P7                     !?::~:               :5:7GY~~~~~~^~~~~^~^!J!7J??YJ?7J7Y!?77~!~~:.~PP~     ");
    System.out.println("^GPPY.                   .??.!7.                :Y. ^5P?~~~~J?JJ??Y~~Y7J?77~!~~^:^:::::::::?GY:      ");
    System.out.println("~GPG?                   .YJ :5?:      .         ~?    ~Y5?!~?!7!!?7^^~~^^^^^^^^^^^^^^^^::!5P!        ");
    System.out.println(":GPPJ                   .??:.^7YJ.   .:~!      .J^      ^?5J7~~~~~~~~^^~~~~~^^^^^^^^^^:~YG?.         ");
    System.out.println(" JGPP:                    .::. :!.::.  ~!      !7         .~JYJ7!~~~~~~~~~~~~~^~^^^^^!YPJ:           ");
    System.out.println(" :PGGJ                  .....:::::::  ::      ~?.            .~?YY?7!~~~~~~~~~~~^^~75P?:             ");
    System.out.println("  ^GGG?               :!!^^:::^^~~^:.    .   ^J.                .:!?YYJ?!~~~~~^~!JP57.               ");
    System.out.println("   ^5GGJ:             .. :!^^^^^^~~~...:^^: ~?.                     .:~7JYYJJ?J5PJ^                  ");
    System.out.println("    .75GP7:                ^~~~~^^::^~^^:. !?.                           .:~!??~.                    ");
    System.out.println("      .~YGGJ~.          ....:::^^~^^:..  .77                                                         ");
    System.out.println("         :!YPPY7^.    .!7~^^^^^:..      ^J~                                                          ");
    System.out.println("            .^7Y55Y?!^:..             .7?:                                                           ");
    System.out.println("                .:~7JY5YJ?7~^::..   .!J~                                                             ");
    System.out.println("                      .:~!7?JJYYYYJYY7.                                                              ");
    System.out.println("                               ..:::.                                                                ");
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                                     "); 
    System.out.println("                                                                                                     "); 
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                                     ");
    System.out.println("                               .:                                                                    ");
    System.out.println("                               #                                                                     ");
    System.out.println("                              -#                                                                     ");
    System.out.println("                             :#=                                                                     ");
    System.out.println("                           .+#=                                                                      ");
    System.out.println("                         :+#*.                                                                       ");
    System.out.println("                       -*#+:    :--:                                                                 ");
    System.out.println("                    .+##=.  .-*+:                                                                    ");
    System.out.println("                  .+##=   .+#+.                                                                      ");
    System.out.println("                 .###:   :##=                                                                        ");
    System.out.println("                 :##=    *##:                                                                        ");
    System.out.println("                  +#=    +###:                                                                       ");
    System.out.println("                   =#:    +###=                                                                      ");
    System.out.println("                    .+=    -###:                                                                     ");
    System.out.println("                      .=.   -#*                                                                      ");
    System.out.println("              ...           =-         ..:-:                                                         ");
    System.out.println("         :-==.                   ...       ==.                                                       ");
    System.out.println("         .:-------------------:::.         -=:                                                       ");
    System.out.println("                                          :=-                                                        ");
    System.out.println("             :=-..          ...::.      :-:                                                          ");
    System.out.println("              .:--==========---::.    ..                                                             ");
    System.out.println("                                                                                                     ");
    System.out.println("               -=::.........::-:                                                                     ");
    System.out.println("                :-============-:.                                                                    ");
    System.out.println("     .:-:.                                :                                                          ");
    System.out.println("    :===-::..                    ...:::::.                                                           ");
    System.out.println("       ...::::----------------::::..    ..:::                                                        ");
    System.out.println("             .................:::::::-::..                                                           ");
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                                     ");
    System.out.println("     .##-                                                                                            ");
    System.out.println("     .##-                                                                                            ");
    System.out.println("     .##-  :=++**+=:  -++.    :++. :=++**+=: .:                                                      ");
    System.out.println("     .##-  ::....=##-  *#+    +#*  .:....-##-                                                        ");
    System.out.println("     .##-       ..##=  -##-  .##-       ..*#=                                                        ");
    System.out.println("     .##-  :=**+++##=   +#*  +#*   .=**+++##=                                                        ");
    System.out.println("     .##- :##:    ##=   .##=:##.  :##:    *#=                                                        ");
    System.out.println("     .##- -##=..:=##=    =##*#-   :##=. .=##=                                                        ");
    System.out.println("     :##-  :=+*+=:-+-     +++-     :=+*+=::+-                                                        ");
    System.out.println("    :*#+                                                                                             ");
    System.out.println("   -#+:                                                                                              ");
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                                     ");
  }
}